// GENERATED by scripts/gen-schema.mjs from spec/schema/influence.v0.json. Do not edit.
export const influenceSchemaV0 = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:influence-disclosure:schema:v0",
  "title": "Influence Disclosure Section, v0",
  "description": "A signed statement of the paid relationships that did or did not shape one agent decision. Designed to be embedded inside a receipt format maintained by someone else, not to be a receipt of its own.",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "spec_version",
    "completeness",
    "relationships"
  ],
  "properties": {
    "spec_version": {
      "description": "Breaking changes are expected throughout 0.x.",
      "const": "0.1.0"
    },
    "completeness": {
      "description": "An explicit assertion by the issuer. `complete` means every paid relationship bearing on this decision is listed. A signature cannot prove completeness; stating it converts a later-discovered omission from silence into an attributable false statement.",
      "enum": [
        "complete",
        "partial"
      ]
    },
    "withheld_reason": {
      "description": "Required when completeness is `partial`. Says why the list is not exhaustive.",
      "enum": [
        "commercially_confidential",
        "not_known_at_issue_time",
        "jurisdictional_restriction",
        "other"
      ]
    },
    "relationships": {
      "description": "May be empty. An empty array under `completeness: complete` is a positive signed claim that no paid relationship bore on this decision, which is different from omitting the section.",
      "type": "array",
      "maxItems": 64,
      "items": {
        "$ref": "#/$defs/relationship"
      }
    }
  },
  "allOf": [
    {
      "if": {
        "properties": {
          "completeness": {
            "const": "partial"
          }
        },
        "required": [
          "completeness"
        ]
      },
      "then": {
        "required": [
          "withheld_reason"
        ]
      },
      "else": {
        "not": {
          "required": [
            "withheld_reason"
          ]
        }
      }
    }
  ],
  "$defs": {
    "relationship": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "id",
        "counterparty",
        "direction",
        "form",
        "compensation",
        "effect"
      ],
      "properties": {
        "id": {
          "description": "Local identifier, unique within this section.",
          "type": "string",
          "pattern": "^[a-z0-9][a-z0-9_-]{0,31}$"
        },
        "counterparty": {
          "$ref": "#/$defs/counterparty"
        },
        "direction": {
          "description": "`inbound`: the issuer receives value. `outbound`: the issuer pays it.",
          "enum": [
            "inbound",
            "outbound"
          ]
        },
        "form": {
          "enum": [
            "commission",
            "paid_placement",
            "affiliate",
            "sponsorship",
            "revenue_share",
            "ownership",
            "exclusivity",
            "data_supply",
            "other"
          ]
        },
        "compensation": {
          "$ref": "#/$defs/compensation"
        },
        "effect": {
          "$ref": "#/$defs/effect"
        },
        "disclosed_to_principal": {
          "description": "Whether the principal was told at decision time, only on request, or not at all. Records what happened; it does not bless any of the three.",
          "enum": [
            "in_band",
            "on_request",
            "not_disclosed"
          ]
        }
      }
    },
    "counterparty": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "ref"
      ],
      "properties": {
        "ref": {
          "description": "Stable identifier of the other party: a domain, a legal entity identifier, or an identifier defined by the host format. An identifier, never prose, and never a natural person.",
          "type": "string",
          "minLength": 1,
          "maxLength": 128,
          "pattern": "^[^\\s]+$"
        },
        "kind": {
          "enum": [
            "merchant",
            "publisher",
            "advertiser",
            "platform",
            "agent",
            "other"
          ]
        }
      }
    },
    "compensation": {
      "oneOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type",
            "rate"
          ],
          "properties": {
            "type": {
              "const": "rate"
            },
            "rate": {
              "description": "Fraction of transaction value, 0 to 1. 0.15 means 15 per cent.",
              "type": "number",
              "minimum": 0,
              "maximum": 1
            }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type",
            "amount",
            "currency"
          ],
          "properties": {
            "type": {
              "const": "fixed"
            },
            "amount": {
              "description": "Decimal string, so that no value is lost to binary floating point.",
              "type": "string",
              "pattern": "^-?[0-9]+(\\.[0-9]+)?$"
            },
            "currency": {
              "type": "string",
              "pattern": "^[A-Z]{3}$"
            }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type"
          ],
          "properties": {
            "type": {
              "const": "none"
            }
          }
        },
        {
          "type": "object",
          "additionalProperties": false,
          "required": [
            "type",
            "reason"
          ],
          "properties": {
            "type": {
              "const": "withheld"
            },
            "reason": {
              "enum": [
                "commercially_confidential",
                "not_known_at_issue_time",
                "jurisdictional_restriction",
                "other"
              ]
            }
          }
        }
      ]
    },
    "effect": {
      "type": "object",
      "additionalProperties": false,
      "required": [
        "kind"
      ],
      "properties": {
        "kind": {
          "description": "What the relationship did to this decision. `none` records a relationship that exists but did not bear on it, which is the disclosure most often skipped.",
          "enum": [
            "none",
            "inclusion",
            "ranking",
            "exclusion",
            "filtering",
            "presentation"
          ]
        },
        "targets": {
          "description": "Opaque references to the options affected, resolved by the host format. This section deliberately does not define the option list; it points into whatever the host already records.",
          "type": "array",
          "minItems": 1,
          "maxItems": 64,
          "items": {
            "type": "string",
            "minLength": 1,
            "maxLength": 128,
            "pattern": "^[^\\s]+$"
          }
        }
      },
      "allOf": [
        {
          "if": {
            "properties": {
              "kind": {
                "not": {
                  "const": "none"
                }
              }
            },
            "required": [
              "kind"
            ]
          },
          "then": {
            "required": [
              "targets"
            ]
          }
        }
      ]
    }
  }
} as const
