// The JSON Schema in /spec is the normative artefact. This copies it into the package
// source so the library and the published schema can never disagree. A test regenerates
// and compares, so drift fails CI rather than shipping.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const root = new URL('../', import.meta.url)
const src = new URL('spec/schema/influence.v0.json', root)
const out = new URL('packages/core/src/schema.generated.ts', root)

const schema = JSON.parse(readFileSync(src, 'utf8'))
const body = `// GENERATED by scripts/gen-schema.mjs from spec/schema/influence.v0.json. Do not edit.
export const influenceSchemaV0 = ${JSON.stringify(schema, null, 2)} as const
`
writeFileSync(fileURLToPath(out), body.replace(/\r\n/g, '\n'), 'utf8')
console.log(`wrote ${fileURLToPath(out)}`)
