"""Subset Noto Sans TC (思源黑體) to the characters this site actually renders.

The site's Chinese copy is fixed and lives in source, so shipping a general-purpose CJK
webfont is pure waste: @fontsource's unicode-range build emits ~105 subsets per weight,
which lands as a 395 kB render-blocking stylesheet and 18 MB of font files, almost none
of which a reader ever fetches.

This scans site/src for CJK characters and cuts three weights down to exactly those.
Re-run it whenever Chinese copy changes; the build does not do it automatically, and a
missing glyph falls back to a system font rather than breaking.

    python tools/subset_fonts.py
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "site" / "src"
FONT_PKG = ROOT / "site" / "node_modules" / "@fontsource" / "noto-sans-tc" / "files"
OUT_FONTS = SRC / "fonts"
OUT_CSS = SRC / "styles" / "noto-sans-tc.css"
WEIGHTS = (300, 400, 500)

# CJK ideographs, the Traditional-Chinese punctuation that sits between them, and the
# fullwidth forms. Latin, digits and Latin punctuation come from Geist, not from here.
CJK = re.compile(
    r"[　-〿"      # CJK punctuation 。、「」《》
    r"㐀-䶿"       # extension A
    r"一-鿿"       # unified ideographs
    r"豈-﫿"       # compatibility ideographs
    r"︰-﹏"       # compatibility forms
    r"＀-￯]"      # fullwidth forms ／ ：（）
)


def collect() -> set[str]:
    chars: set[str] = set()
    for path in sorted(SRC.rglob("*")):
        if path.is_dir() or path.suffix.lower() in {".woff2", ".woff", ".ttf", ".otf", ".png"}:
            continue
        chars.update(CJK.findall(path.read_text(encoding="utf-8", errors="ignore")))
    return chars


def main() -> int:
    chars = collect()
    if not chars:
        print("no CJK characters found under site/src; nothing to do")
        return 1

    OUT_FONTS.mkdir(parents=True, exist_ok=True)
    unicodes = ",".join(f"U+{ord(c):04X}" for c in sorted(chars))

    faces = []
    total = 0
    for weight in WEIGHTS:
        source = FONT_PKG / f"noto-sans-tc-chinese-traditional-{weight}-normal.woff2"
        if not source.exists():
            print(f"missing source font: {source}", file=sys.stderr)
            return 1
        target = OUT_FONTS / f"noto-sans-tc-{weight}.woff2"
        subprocess.run(
            [
                sys.executable, "-m", "fontTools.subset", str(source),
                f"--unicodes={unicodes}",
                "--flavor=woff2",
                "--layout-features=",       # no GSUB/GPOS needed for this copy
                "--no-hinting",
                "--desubroutinize",
                f"--output-file={target}",
            ],
            check=True,
            capture_output=True,
        )
        size = target.stat().st_size
        total += size
        print(f"  {target.name}  {size / 1024:>6.1f} KB")
        faces.append(
            "@font-face {\n"
            "  font-family: 'Noto Sans TC';\n"
            "  font-style: normal;\n"
            f"  font-weight: {weight};\n"
            "  font-display: swap;\n"
            f"  src: url('../fonts/noto-sans-tc-{weight}.woff2') format('woff2');\n"
            "}\n"
        )

    header = (
        "/* GENERATED by tools/subset_fonts.py. Do not edit.\n"
        f"   Noto Sans TC (思源黑體) cut to the {len(chars)} CJK characters this site renders.\n"
        "   Re-run the script after changing Chinese copy. */\n\n"
    )
    OUT_CSS.write_text(header + "\n".join(faces), encoding="utf-8", newline="\n")
    print(f"{len(chars)} characters, {total / 1024:.1f} KB across {len(WEIGHTS)} weights -> {OUT_CSS.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
